added an overview
Cray-HPE/hms-sls pull request #45
Opened 2022-03-22 18:46 UTC by nieuwsma

### Summary and Scope

EXPLAIN WHY THIS PR IS NECESSARY. WHAT IS IMPACTED?
IS THIS A NEW FEATURE OR CRITICAL BUG FIX? SUMMARIZE WHAT CHANGED.

DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  Y/N

REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? E.G., .spec, Chart.yaml, .version, CHANGELOG.md

REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y/N

### Issues and Related PRs

LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.

* Resolves CASM-XYZ
* Change will also be needed in `<insert branch name here>`
* Future work required by CASM-ABC
* Merge with `<insert PR URL here>`
* Merge before `<insert PR URL here>`
* Merge after `<insert PR URL here>`

### Testing

LIST THE ENVIRONMENTS IN WHICH THESE CHANGES WERE TESTED.

Tested on:

* `<drink system>`
* Craystack
* CMS base-box
* Virtual Shasta

Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc)
Were continuous integration tests run? Y/N   If not, Why?
Was an Upgrade tested?                 Y/N   If not, Why?
Was a Downgrade tested?                Y/N   If not, Why?
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?

WHAT WAS THE EXTENT OF TESTING PERFORMED? MANUAL VERSUS AUTOMATED TESTS (UNIT/SMOKE/OTHER)
HOW WERE CHANGES VERIFIED TO BE SUCCESSFUL?

### Risks and Mitigations

HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh)
ARE THERE KNOWN ISSUES WITH THESE CHANGES?
ANY OTHER SPECIAL CONSIDERATIONS?

INCLUDE THE FOLLOWING ITEMS THAT APPLY. LIST ADDITIONAL ITEMS AND PROVIDE MORE DETAILED INFORMATION AS APPROPRIATE.

Requires:

* Additional testing on bare-metal
* Compute nodes
* 3rd party software
* Broader integration testing
* Fresh install
* Platform upgrade

2022-03-23 14:59 UTC, mjendrysik-hpe requested changes

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +* Source of truth for HMS Serviers (MEDS, REDS, HMS-Discovery, and HSM) when trying to identify and discovery new hardware in the system
s/Serviers/Services

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +  * A logical concept. We have allocated a CIDR/IP Address range for a specific purpose. Examples include the
Move **Examples include the** to a new line and make it
* Examples include:

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +* A SLS Subnet is…
A SLS Subnet can consist of:
* DHCP Address pool
* etc etc

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +  * Looks to SLS for what Mountain/Hill cabinets are in the system
Really strange sentence for a tech doc. Simplify it, for example:
Queries SLS for Mountain/Hill cabinets

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +  * IP Reservations to populate static DNS records. Like packages.local, registry.local, and api-gw-service-nmn.local
Use an **Examples include:** format.

2022-03-23 14:59 UTC, mjendrysik-hpe commented on docs/overview.md
> +  * Node Alias information. For example for the node x3000c0s19b1n0, look to SLS to create a DNS entry for the friendly name automatically ncn-000001-nmn.
Use an **Examples include:** format.

2022-04-11 14:20 UTC, shunr-hpe approved these changes

2022-04-11 18:38 UTC, merged